### ISSUE TITLE
Compatibility with iyzico WooCommerce

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#124]
**Describe the bug**
In our plugin, we can't save the setting for this payment gateway 

**To Reproduce**
1. Install this plugin: 
[iyzico-woocommerce.zip](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/files/10520515/iyzico-woocommerce.zip)
2. Set fees and save the settings.
3. And then refresh the page. 

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/47939

**Comment by nidhitatosaniya** [comment]
@Chetna1510 Actually issue is in Valid_api.js file. it is not our plugin's file. It's a IYZICO plugin's file.

**Comment by ashokrane** [comment]
@nidhitatosaniya Please talk about this with @kartikparmar & decide on next course of action for this issue (like what reply is to be sent to client).

**Comment by kartikparmar** [comment]
@nidhitatosaniya as we discussed on the call, we can dequeue that file from being loaded on our settings page instead of making any changes in iyzico WooCommerce plugin file. 

Along with that, please ask the client to contact the plugin author to make the correction in their plugin as well so that their files get loaded only on their settings page.
