### ISSUE TITLE
Allow the option to show fees on shopping cart page before a payment method is selected.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#187]
**Is your feature request related to a problem? Please describe.**
Fees are not visible when I’m on my shopping cart page. They become visible when I enter the checkout and stay visible when I go back to the shopping cart page.

So it doesn’t appear on the initial shopping cart visit.
“Hiding on shopping cart” is not turned on.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://wordpress.org/support/topic/additional-fees-not-visible-on-initial-shopping-cart-page-visit

**Comment by apeksha10** [comment]
The above issue is replicated when I add the fees at the product level.
Fees are not visible when I’m on the cart page. They become visible when I visit the checkout page and stay visible when I go back to the cart page.

Video: https://app.screencast.com/jRJGN1MObkuwv

Note: The fix is working fine at a global level. 

Hence I am re-opening this issue

**Comment by mital-tyche** [comment]
Hello @apeksha10 ,
https://watch.screencastify.com/v/JxxNDj1kE67uKQipFbHj
It is working fine from my side kindly please check attached video. One more thing is that you need to check previous order payment getaway. because it is working based on previously selected Payment method.
