### ISSUE TITLE
Compatibility with WPML

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#36]
The client is having an issue where he is unable to translate the payment gateway fee titles in different languages.

Link: https://wordpress.org/support/topic/wpml-support-113/

**Comment by Shasvat7** [comment]
Here, the payment gateway titles on the admin side: https://prnt.sc/1tbujsu are coming from the Woo filter.
We are using the filter `woocommerce_get_sections_alg_checkout_fees` and in the function, we use this Woo function to fetch the payment gateways `WC()->payment_gateways->payment_gateways()` and to pass the array of payment gateways titles and are shown from there so we cannot add this titles in the .pot files.
And for the payment gateway fees titles coming on the checkout are added by the admin from here: https://prnt.sc/1t8a1so which is not constant and we will not have the values to add it in the .pot files.

Translations of the string are done from the .pot files through WPML but due to the above reason, they are not getting translated. Thus, closing this issue.

**Comment by apeksha10** [comment]
As per @Shasvat7 comment no need to test this issue.

So I am putting a fixed label
