### ISSUE TITLE
Even when Info option is enabled, only the COD payment gateway is not visible on the product page. 

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#39]
The client is having an issue where COD payment gateway is not shown on the product page even when the Info option is enabled. However, all other payment gateways are shown.

I have tried to replicate the issue but was unable to replicate it. The issue is faced on the client-side only.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/19015

**Comment by Shasvat7** [comment]
COD payment method will not come on the product when the COD payment method is based on the shipping methods. Hence, unless the shipping option is not selected on the cart/checkout page COD payment will not be count as the available payment gateways by the WooCommerce, and due to which it is not shown in the info table on the product page.

We use the Woo function `WC()->payment_gateways->get_available_payment_gateways()` in which only the available gateway is passed by the Woo and it will pass the COD payment method only if the shipping option is selected.
Also, besides using this function, we can use the Woo function `WC()->payment_gateways->payment_gateways()` which contains all the installed payments method but using this function will show those payment methods also which are kept disabled in the Woo so we cannot use this function.

The current behavior is correct and working properly only, hence closing this as this is not an issue.

**Comment by apeksha10** [comment]
As per @Shasvat7 comment no need to test this issue.

So I am putting a fixed label
