### ISSUE TITLE
Payment Gateway fee is not added on the Order Receive page when working with the WooCommerce Deposit plugin.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/checkout-fees-for-woocommerce#50]
**Describe the bug**
The issue is that the payment gateway fee is not added to the Order Receive page after placing an order when we work with the WooCommerce Deposit plugin.

**To Reproduce**
1) Install the WooCommerce Deposit plugin. 
[woocommerce-deposits-3.0.latest-1.zip](https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/files/5627791/woocommerce-deposits-3.0.latest-1.zip)
2) Create a deposit product.
3) Create a coupon amount greater than the deposit amount.
4) Add the product to the cart.
5) On the checkout page, select any payment gateway for which you have set the fees.
6) Enter the coupon code which is created.
6) Place an order. You will not see the fees included on the Order receive page.

**Expected behavior**
The payment gateway fees should be included.

**Screenshots**
1) Checkout page: https://prnt.sc/vu4jks
2) Order Receive page: https://prnt.sc/vu4ik4

One more issue he has described that we need to refresh the page after removing the coupon code to see the gateway fees.

Steps mentioned by the client itself in the forum: https://wordpress.org/support/topic/when-coupons-removed-screen-does-not-refresh-properly/

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/22787

**Comment by Chetna1510** [comment]
One more client has reported the bug with this deposit plugin.

https://wordpress.org/support/topic/incompatible-with-deposits/#post-14705036

I tried testing it with Woocommerce Deposits.

Full Price: 3,220
Deposit: 500

Creditcard fee(3.7%): 119.14
total: 619.14

It calculated the fee of the full amount instead of just the deposit amount which should just be 500 x 3.7% = 18.5.

When I tested to pay the remaining balance, it would calculate again for that payment gateway. So paying for the fee of the full amount when you’re paying just for the deposit is kinda an issue.

-------

I had a word with the team and they mention that you can tell the client that we haven’t tested the compatibility yet with those 2 plugins.

**Comment by Chetna1510** [comment]
One more client has reported this - https://wordpress.org/support/topic/fees-being-applied-to-full-amount-when-paying-deposit/

 our website accepts deposits. The 4% we are adding to payments is calculating the fee:
Deposit = full amount (not deposit amount) e.g. 4% on $2,900, not 4% on $500
Balance = balance amount e.g. 4% on $2,400

We are using this deposit plugin: https://woocommerce.com/products/woocommerce-deposits/

Expecting behavior could be:

1. Allow the option if the fees will be applied to the deposit amount or full amount
2. If the fees apply on deposit amount, then fees should be applied again while paying partial amount
3. If the fee is applied on the full amount in the first order, then fees shouldn't be applied again while paying the partial amount - Due to this issue, I couldn't tell the client that the fees will apply on full amount and won't apply on the partial amount in future pay.

**Comment by mital-tyche** [comment]
This one is not replicating on my side. I checked with all of client ticket.
Our fees cut only one time when main order is placed... In Partial Payments Fees is not added.
Here is SS regrading main order and partial payment order.
https://prnt.sc/gRbAh0Qe_9Cb
https://prnt.sc/xbkvQUOP5pYy

Also, After applying coupon fees is added Order Receive page
https://prnt.sc/vvxx7d6hcSaa

All the issue is reported in 2020 & 2021. after this we add compability with woocommerce-deposits.
check this function 'alc_wc_deposits_for_wc_compatibility' in plugins\checkout-fees-for-woocommerce\includes\class-alg-wc-order-fees.php
