### ISSUE TITLE
Orders are getting duplicated when our plugin is activated.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#83]
**Describe the bug**
We’re having an issue where multiple Pending payment orders are being placed when a client uses the back button to swap payment methods.

**To Reproduce**
I'm also able to replicate the issue on my staging site. 

1. I selected Payment Gateway 1 at Checkout and then Place Order
2. Payment gateway page loads then I used the browser “Back” button to return to to site’s Checkout page
3. In another Tab – I checked in wp-admin, and saw that new Order was in with Pending payment status under WooCommerce > Orders
4. Back on the on the Checkout page, I selected Payment Gateway 2 at Checkout and then Clicked Place Order and processed payment
5. I checked in wp-admin, and saw that there’s now a second Order with Paid/Pending status under WooCommerce > Orders

This is only happening with the payment methods that have Payment Gateway Fees enabled.
I disabled the plugin and the duplicate orders aren't being created.

I had used PayPal as a first option and COD as a second option. - https://prnt.sc/1ubx5bm

**Additional context**
https://wordpress.org/support/topic/duplicate-pending-payment-orders/

**Comment by Shasvat7** [comment]
@Chetna1510 I have checked this issue, and also it gets replicated but this happens because when we change the payment method the total amount of the order gets changed and due to which WooCommerce count it as a new order.
I tried by keeping the same payment gateway fees for two different methods and followed the same steps, in that case the total amount of the order doesn't gets changed and due to which duplicate order is not created.

I have checked this behavior by entering the coupon code after clicking the back button in the browser, and than selecting other payment gateway and placing the order, here also the new order will be created.

So you can tell the client about this WooCommerce behavior.
